website/views/acct_mgmt_views.py
"""
Manages all routes related to account management

Author: Mathew Owusu Jr
"""


from flask import Blueprint, Response, render_template, redirect, request, flash, url_for
from flask_login import login_user, login_required, logout_user, current_user
from werkzeug.security import generate_password_hash, check_password_hash
from ..models import Customer, Cart
from .. import db

acct_mgmt_views = Blueprint('acct_mgmt_views', __name__)


@acct_mgmt_views.route('/signup', methods=["GET"])
def display_signup_page():
    """
    Displays the signup page

    Returns:
        A rendered HTML template
    """
    return render_template('acct_mgmt/signup.html', 
    current_user=current_user)


@acct_mgmt_views.route('/signup', methods=["POST"])
def signup():
    """
    The business logic for signing up/account creation

    Returns:
        Redirects the page to the home page if the process is successful
        else it redirects back to the signup page
    """
    if Customer.query.filter_by(email=request.form['email']).first():
        flash("Email is Taken", category="email")
        return redirect('/signup')
    elif request.form['password_1'] != request.form['password_2']:
        flash("Passwords do not match", category="password")
        return redirect('/signup')
    else:
        new_customer = Customer(
            firstname = request.form['firstname'],
            lastname = request.form['lastname'],
            email = request.form['email'],
            password_hash = generate_password_hash(request.form['password_1'], method='sha256')
        )
        db.session.add(new_customer)
        # db.session.commit()
        user_cart = Cart()
        db.session.add(user_cart)

        new_customer.cart = user_cart
        db.session.add(new_customer)

        db.session.commit()
        login_user(new_customer, remember=True)
        return redirect(url_for('home_view.home_page'))


@acct_mgmt_views.route('/login', methods=["GET"])
def display_login_page():
    """
    Displays the login page

    Returns:
        A rendered HTML template
    """
    return render_template('acct_mgmt/login.html', 
    current_user=current_user)


@acct_mgmt_views.route('/login', methods=["POST"])
def login():
    """
    The business logic for logging into an account

    Returns:
        Redirects the page to the account management page
    """
    email = request.form['email']
    password = request.form['password']
    user = Customer.query.filter_by(email=email).first()
    if user:
        if check_password_hash(user.password_hash, password):
            login_user(user, remember=True)
            return redirect(url_for('home_view.home_page'))
    return redirect(url_for('acct_mgmt_views.login'))


@acct_mgmt_views.route('/user/<int:user_id>', methods=['GET'])
@login_required
def display_account_page(user_id):
    """
    Display the a users account information

    Parameters:
        user_id (int): The id of the user being accessed

    Returns:
        A rendered HTML template
    """
    return render_template('acct_mgmt/mg_acct.html', 
    current_user=current_user)


@acct_mgmt_views.route('/logout')
@login_required
def logout():
    """
    Logs the currently signed in user out

    Returns:
        Redirects the page to the display login page
    """
    logout_user()
    return redirect(url_for('acct_mgmt_views.display_login_page'))


@acct_mgmt_views.route('/user/<int:user_id>/email', methods=['PUT'])
@login_required
def change_email(user_id):
    """
    Changes the user email address
    
    Parameters:
        user_id (int): The id of the user being accessed

    Returns:
        HTTP Reponse: Send the url for the display account page and a http status
        of 200 for success
    """
    data = request.get_json()
    user = Customer.query.get_or_404(user_id)
    old_email = data['old_email']
    new_email = data['new_email']
    if old_email == user.email:
        user.email = new_email
        db.session.add(user)
        db.session.commit()
        return Response(url_for('acct_mgmt_views.display_account_page', user_id=user_id), 200)
    else:
        return Response('', 400)



@acct_mgmt_views.route('/user/<int:user_id>/password', methods=['PUT'])
@login_required
def change_password(user_id):
    """
    Changes the user's password

    Parameters:
        user_id (int): The id of the user being accessed

    Returns:
        HTTP Reponse: Send the url for the display account page and a http status
        of 200 for success
    """
    data = request.get_json()
    user = Customer.query.get_or_404(user_id)
    old_passord = data['old_pass']
    new_passord = data['new_pass']
    if check_password_hash(user.password_hash, old_passord):
        user.password_hash = generate_password_hash(new_passord, method='sha256')
        db.session.add(user)
        db.session.commit()
        return Response(url_for('acct_mgmt_views.display_account_page', user_id=user_id), 200)
    else:
        return Response('', 400)


@acct_mgmt_views.route('/user/<int:user_id>', methods=['DELETE'])
@login_required
def delete_account(user_id):
    """
    Deletes a user's account

    Parameters:
        user_id (int): The id of the user being accessed

    Returns:
        HTTP Reponse: Send the url for the display signup page and a http status
        of 200 for success
    """
    user = Customer.query.get_or_404(user_id)
    db.session.delete(user)
    db.session.commit()
    logout_user()
    return Response(url_for('acct_mgmt_views.display_signup_page'), 200)

website/views/cust_cart_views.py
"""
Manages all routes related to the current user's cart

Author: Mathew Owusu Jr
"""


from flask import Blueprint, Response, render_template, redirect, request, url_for
from flask_login import login_required, current_user
from ..models import Quantity_Per_Size, ReservedShoe, Shoe, Color
cust_cart_views = Blueprint('cust_cart_views', __name__)
from .. import db


@cust_cart_views.before_request
@login_required
def login_to_access():
    """
    Acts as a middle ware that ensure none of this blueprints routes can be
    accessed if no user is currently logged in
    """
    pass


@cust_cart_views.route('/cart', methods=['GET'])
def display_cart_page():
    """
    Display the user's cart

    Returns:
        A rendered HTML template
    """
    cart = current_user.cart.shoes
    total_price = 0
    for shoe in cart:
        total_price += (shoe.quantity * shoe.reserved_shoe.price)
        
    return render_template('acct_mgmt/cart.html', 
    current_user=current_user, 
    cart=cart, 
    total_price=total_price)


@cust_cart_views.route('/cart', methods=['POST'])
def add_to_cart():
    """
    Adds a shoe to the user's cart

    Returns:
        Redirects the page to cart page again
    """
    id = int(request.form['shoe_id'])
    quantity = int(request.form['quantity'])
    color = (request.form['color'])
    size = float(request.form['size'])

    user_cart = current_user.cart
    shoe_in_cart = ReservedShoe.query.filter_by(
        cart_id=user_cart.id, 
        shoe_id=id,
        color=color,
        size=size).first()

    if shoe_in_cart:
        color = Color.query.filter_by(shoe_id=shoe_in_cart.shoe_id).first()
        max_quantity = Quantity_Per_Size.query.filter_by(color_id=color.id, size=shoe_in_cart.size).first()
        if max_quantity.quantity >= (shoe_in_cart.quantity + quantity):
            shoe_in_cart.quantity += quantity
            db.session.commit()
        # else you exceeded the max quantity
        else:
            return ('', 204)
    else:
        added_shoe = ReservedShoe(
            quantity = quantity,
            color=request.form['color'],
            size=request.form['size']
        )
        added_shoe.reserved_shoe = Shoe.query.get_or_404(id)
        db.session.add(added_shoe)
        current_user.cart.shoes.append(added_shoe)
        db.session.add(current_user)

        db.session.commit()

    return redirect(url_for('cust_cart_views.display_cart_page'))


@cust_cart_views.route('/cart/<int:id>', methods=['POST'])
def quick_add(id):
    """
    Adds to the quantity of a shoe in the user's cart

    Parameters:
        id (int): The id of the cart item

    Returns:_description_
        HTTP Reponse: Send the url for the display cart page and a http status
        of 200 for success
    """
    shoe = ReservedShoe.query.get_or_404(id)
    color = Color.query.filter_by(shoe_id=shoe.shoe_id).first()
    max_quantity = Quantity_Per_Size.query.filter_by(color_id=color.id, size=shoe.size).first()
    if max_quantity.quantity >= (shoe.quantity + 1):
        shoe.quantity += 1
    db.session.commit()
    return Response(url_for('cust_cart_views.display_cart_page'), 200)


@cust_cart_views.route('/cart/<int:id>', methods=['DELETE'])
def quick_remove(id):
    """
    Removes from the quantity of a shoe in the user's cart

    Parameters:
        id (int): The id of the cart item

    Returns:_description_
        HTTP Reponse: Send the url for the display cart page and a http status
        of 200 for success
    """
    shoe = ReservedShoe.query.get_or_404(id)
    shoe.quantity -= 1
    if shoe.quantity == 0:
        db.session.delete(shoe)
    db.session.commit()
    return Response(url_for('cust_cart_views.display_cart_page'), 200)


@cust_cart_views.route('/cart/remove/<int:id>', methods=['DELETE'])
def remove_from_cart(id):
    """
    Removes a shoe from the user's cart

    Parameters:
        id (int): The id of the cart item

    Returns:
        HTTP Reponse: Send the url for the display cart page and a http status
        of 200 for success
    """
    shoe = ReservedShoe.query.get_or_404(id)
    db.session.delete(shoe)
    db.session.commit()
    return Response(url_for('cust_cart_views.display_cart_page'), 200)

website/views/cust_catalog_views.py
"""
Manages all routes related to the shoe catalog that the customers see

Author: Mathew Owusu Jr
"""


from flask import Blueprint, render_template, request
from flask_login import current_user
from ..models import Shoe


PER_PAGE = 36
cust_catalog_views = Blueprint('cust_catalog_views', __name__)


@cust_catalog_views.route('/releases', methods=['GET'])
def releases_page():
    """
    Display all the shoes from the database

    Returns:
        A rendered HTML template
    """
    title = "New Releases"
    page = request.args.get('page', 1, type=int)
    collection = Shoe.query.paginate(page=page, per_page=PER_PAGE)
    routeUrl = 'cust_catalog_views.releases_page'

    return render_template('customer/catalog.html', 
    current_user=current_user, 
    title=title, 
    collection=collection, 
    routeUrl=routeUrl)


@cust_catalog_views.route('/mens/releases', methods=['GET'])
def mens_releases_page():
    """
    Display all the mens shoes from the database

    Returns:
        A rendered HTML template
    """
    title = "New Releases"
    page = request.args.get('page', 1, type=int)
    collection = Shoe.query.filter_by(audience="Men").paginate(page=page, per_page=PER_PAGE)
    routeUrl = 'cust_catalog_views.mens_releases_page'

    return render_template('customer/catalog.html', 
    title=title, 
    collection=collection, 
    routeUrl=routeUrl)


@cust_catalog_views.route('/womens/releases', methods=['GET'])
def womens_releases_page():
    """
    Display all the womens shoes from the database

    Returns:
        A rendered HTML template
    """
    title = "New Releases"
    page = request.args.get('page', 1, type=int)
    collection = Shoe.query.filter_by(audience="Women").paginate(page=page, per_page=PER_PAGE)
    routeUrl = 'cust_catalog_views.womens_releases_page'

    return render_template('customer/catalog.html', 
    title=title, 
    current_user=current_user, 
    collection=collection, 
    routeUrl=routeUrl)


@cust_catalog_views.route('/kids/releases', methods=['GET'])
def kids_releases_page():
    """
    Display all the kids shoes from the database

    Returns:
        A rendered HTML template
    """
    title = "New Releases"
    page = request.args.get('page', 1, type=int)
    collection = Shoe.query.filter_by(audience="Children").paginate(page=page, per_page=PER_PAGE)
    routeUrl = 'cust_catalog_views.kids_releases_page'

    return render_template('customer/catalog.html', 
    title=title, 
    current_user=current_user, 
    collection=collection, 
    routeUrl=routeUrl)


@cust_catalog_views.route('/<string:brand>/releases', methods=['GET'])
def brand_releases_page(brand):
    """
    Display all the shoes from a particular brand

    Parameters:
        brand (string): The name of the brand

    Returns:
        A rendered HTML template
    """
    title = brand + " New Releases"
    page = request.args.get('page', 1, type=int)
    collection = Shoe.query.filter(Shoe.brand.like('%'+brand+'%')).paginate(page=page, per_page=PER_PAGE)
    routeUrl = 'cust_catalog_views.brand_releases_page'

    return render_template('customer/catalog.html', 
    title=title, 
    current_user=current_user, 
    collection=collection, 
    routeUrl=routeUrl,
    brand=brand)


@cust_catalog_views.route('/releases/browse/<string:searchQuery>')
def search_any_product(searchQuery):
    """
    Display all the shoes that match the search term

    Parameters:
        searchQuery (string): The seach term

    Returns:
        A rendered HTML template
    """
    title = "Sneaker Head Releases"
    page = request.args.get('page', 1, type=int)
    collection = Shoe.query.filter(Shoe.name.like('%'+searchQuery+'%') | Shoe.brand.like('%'+searchQuery+'%')).paginate(page=page, per_page=PER_PAGE)
    routeUrl = 'cust_catalog_views.search_any_product'

    return render_template('customer/catalog.html', 
    title=title, 
    collection=collection, 
    routeUrl=routeUrl,
    searchQuery=searchQuery)


@cust_catalog_views.route('/product/<int:id>', methods=['GET'])
def display_product(id):
    """

    Parameters:
        id (int): The id of the shoe being displayed

    Returns:
        A rendered HTML template
    """
    shoe = Shoe.query.get_or_404(id)
    return render_template('customer/product.html', 
    current_user=current_user, 
    shoe=shoe)
    

website/templates/acct_mgmt/cart.html
{% extends 'base.html' %}

{% block title %}Shopping Cart{% endblock %}

{% block body %}
    <h1>Shopping Cart</h1>
    {% if cart | length > 0 %}
        <table>
            {% for shoe in cart%}
                <tr>
                    <td>
                        <a href="{{url_for('cust_catalog_views.display_product', id=shoe.reserved_shoe.id)}}">
                            {{shoe.reserved_shoe.name}}
                        </a>
                    </td>
                    <td>{{shoe.color}}</td>
                    <td>{{shoe.size}}</td>
                    <td>${{shoe.reserved_shoe.price}}</td>
                    <td>
                        Qty: {{shoe.quantity}}
                        <button onclick="modCartQty('{{url_for('cust_cart_views.quick_add', id=shoe.id)}}', 'POST')">
                            +
                        </button>
                        <button onclick="modCartQty('{{url_for('cust_cart_views.quick_remove', id=shoe.id)}}', 'DELETE')">
                            -
                        </button>
                    </td>
                    <td>
                        <a onclick="sendDeleteRequest('{{url_for('cust_cart_views.remove_from_cart', id=shoe.id)}}')">
                            remove from cart
                        </a>
                    </td>
                </tr>
            {% endfor %}
        </table>
        <h3>Total Price: ${{ total_price }}</h3>
        <form action="{{url_for('transcations_views.display_transcations')}}" method="POST">
            <input type="submit" value="Checkout Cart">
        </form>
    {% else %}
        <p>Sad empty cart :(</p>
        <p>Go add some items into your cart to make it happy</p>
    {% endif %}
{% endblock %}

website/templates/acct_mgmt/login.html
{% extends 'base.html' %}

{% block title %}Sign In{% endblock %}

{% block body %}
    <h1>Sneaker Head</h1>
    <div class="login">
        <h2>Sign-In</h2>
        <form class="content" action="{{url_for('acct_mgmt_views.login')}}" method="POST">
            <input class="signup" name="email" type="email" placeholder="Email" required>

            <input class="signup" name="password" type="password" placeholder="Password" required>

            <input type="submit" value="Sign In">
        </form> 
    </div>
    
    <p class="login-pg-p">New to Sneaker Head?</p>
    <button class="login-pg-sign-btn" onclick="redirectUrl('{{url_for('acct_mgmt_views.signup')}}')">
        Create your Sneaker Head Account
    </button>
{% endblock %}

website/templates/acct_mgmt/mg_acct.html
{% extends 'base.html' %}

{% block title %}{{current_user.firstname}}{% endblock %}

{% block body %}
    <h1>Welcome {{current_user.firstname}} {{current_user.lastname}}</h1>
    <div class="mg-account">
        <h2>View Transcations</h2>
        <a href="{{url_for('transcations_views.display_transcations')}}"
        class="past-transcations">Past Transcations</a>

        <h2>Change Email</h2>
        <form id="put-form" action="{{url_for('acct_mgmt_views.change_email', user_id=current_user.id)}}">
            <input type="email" name="old_email" placeholder="Enter Current Email" required>
            <input type="email" name="new_email" placeholder="Enter New Email" required>
            <input type="submit" value="Change Email">
        </form>

        <h2>Change Password</h2>
        <form id="put-form" action="{{url_for('acct_mgmt_views.change_password', user_id=current_user.id)}}">
            <input type="password" name="old_pass" placeholder="Enter Current Password" required>
            <input type="password" name="new_pass" placeholder="Enter New Password" required>
            <input type="submit" value="Change Password">
        </form>

        <form>
            <input type="submit" value="Delete Account" onclick="sendDeleteRequest('/user/{{current_user.id}}')">
        </form>
    </div>
{% endblock %}

website/templates/acct_mgmt/signup.html
{% extends 'base.html' %}

{% block title %}Sign Up{% endblock %}

{% block body %}
    <h1>BECOME A SNEAKER Head MEMBER</h1>
    <div class="login">
        <h2>Sign-Up</h2>
        <form class="content" action="{{url_for('acct_mgmt_views.signup')}}" method="POST">
            <input class="signup" name="firstname" type="text" placeholder="First Name" required>
            <input class="signup" name="lastname" type="text" placeholder="Last Name" required>
            <input class="signup" name="email" type="email" placeholder="Email" required>
            <!-- {% with message = get_flashed_messages(with_categories=email) %}
                {% if category == 'email' %}
                    {{ message }}
                {% endif %}
            {% endwith%} -->

            <input class="signup" name="password_1" type="password" placeholder="Password" required>
            <input class="signup" name="password_2" type="password" placeholder="Retype Password" required>
            <!-- {% with message = get_flashed_messages(with_categories=password) %}
                {% if category == 'password' %}
                    {{ message }}
                {% endif %}
            {% endwith%} -->

            <input type="submit" value="Sign Up">
        </form> 
    </div>
    <p class="login-pg-p">Already have an Account?</p>
    <button class="login-pg-sign-btn" onclick="redirectUrl('{{url_for('acct_mgmt_views.login')}}')">
        Sign-In Instead
    </button>
{% endblock %}