website/views/acct_mgmt_views.py
"""
Manages all routes related to account management

Author: Mathew Owusu Jr
"""


from flask import Blueprint, Response, render_template, redirect, request, flash, url_for
from flask_login import login_user, login_required, logout_user, current_user
from werkzeug.security import generate_password_hash, check_password_hash
from ..models import Customer, Cart
from .. import db

acct_mgmt_views = Blueprint('acct_mgmt_views', __name__)


@acct_mgmt_views.route('/signup', methods=["GET"])
def display_signup_page():
    """
    Displays the signup page

    Returns:
        A rendered HTML template
    """
    return render_template('acct_mgmt/signup.html', 
    current_user=current_user)


@acct_mgmt_views.route('/signup', methods=["POST"])
def signup():
    """
    The business logic for signing up/account creation

    Returns:
        Redirects the page to the home page if the process is successful
        else it redirects back to the signup page
    """
    if Customer.query.filter_by(email=request.form['email']).first():
        flash("Email is Taken", category="email")
        return redirect('/signup')
    elif request.form['password_1'] != request.form['password_2']:
        flash("Passwords do not match", category="password")
        return redirect('/signup')
    else:
        new_customer = Customer(
            firstname = request.form['firstname'],
            lastname = request.form['lastname'],
            email = request.form['email'],
            password_hash = generate_password_hash(request.form['password_1'], method='sha256')
        )
        db.session.add(new_customer)
        # db.session.commit()
        user_cart = Cart()
        db.session.add(user_cart)

        new_customer.cart = user_cart
        db.session.add(new_customer)

        db.session.commit()
        login_user(new_customer, remember=True)
        return redirect(url_for('home_view.home_page'))


@acct_mgmt_views.route('/login', methods=["GET"])
def display_login_page():
    """
    Displays the login page

    Returns:
        A rendered HTML template
    """
    return render_template('acct_mgmt/login.html', 
    current_user=current_user)


@acct_mgmt_views.route('/login', methods=["POST"])
def login():
    """
    The business logic for logging into an account

    Returns:
        Redirects the page to the account management page
    """
    email = request.form['email']
    password = request.form['password']
    user = Customer.query.filter_by(email=email).first()
    if user:
        if check_password_hash(user.password_hash, password):
            login_user(user, remember=True)
            return redirect(url_for('home_view.home_page'))
    return redirect(url_for('acct_mgmt_views.login'))


@acct_mgmt_views.route('/user/<int:user_id>', methods=['GET'])
@login_required
def display_account_page(user_id):
    """
    Display the a users account information

    Parameters:
        user_id (int): The id of the user being accessed

    Returns:
        A rendered HTML template
    """
    return render_template('acct_mgmt/mg_acct.html', 
    current_user=current_user)


@acct_mgmt_views.route('/logout')
@login_required
def logout():
    """
    Logs the currently signed in user out

    Returns:
        Redirects the page to the display login page
    """
    logout_user()
    return redirect(url_for('acct_mgmt_views.display_login_page'))


@acct_mgmt_views.route('/user/<int:user_id>/email', methods=['PUT'])
@login_required
def change_email(user_id):
    """
    Changes the user email address
    
    Parameters:
        user_id (int): The id of the user being accessed

    Returns:
        HTTP Reponse: Send the url for the display account page and a http status
        of 200 for success
    """
    data = request.get_json()
    user = Customer.query.get_or_404(user_id)
    old_email = data['old_email']
    new_email = data['new_email']
    if old_email == user.email:
        user.email = new_email
        db.session.add(user)
        db.session.commit()
        return Response(url_for('acct_mgmt_views.display_account_page', user_id=user_id), 200)
    else:
        return Response('', 400)



@acct_mgmt_views.route('/user/<int:user_id>/password', methods=['PUT'])
@login_required
def change_password(user_id):
    """
    Changes the user's password

    Parameters:
        user_id (int): The id of the user being accessed

    Returns:
        HTTP Reponse: Send the url for the display account page and a http status
        of 200 for success
    """
    data = request.get_json()
    user = Customer.query.get_or_404(user_id)
    old_passord = data['old_pass']
    new_passord = data['new_pass']
    if check_password_hash(user.password_hash, old_passord):
        user.password_hash = generate_password_hash(new_passord, method='sha256')
        db.session.add(user)
        db.session.commit()
        return Response(url_for('acct_mgmt_views.display_account_page', user_id=user_id), 200)
    else:
        return Response('', 400)


@acct_mgmt_views.route('/user/<int:user_id>', methods=['DELETE'])
@login_required
def delete_account(user_id):
    """
    Deletes a user's account

    Parameters:
        user_id (int): The id of the user being accessed

    Returns:
        HTTP Reponse: Send the url for the display signup page and a http status
        of 200 for success
    """
    user = Customer.query.get_or_404(user_id)
    db.session.delete(user)
    db.session.commit()
    logout_user()
    return Response(url_for('acct_mgmt_views.display_signup_page'), 200)

website/views/cust_cart_views.py
"""
Manages all routes related to the current user's cart

Author: Mathew Owusu Jr
"""


from flask import Blueprint, Response, render_template, redirect, request, url_for
from flask_login import login_required, current_user
from ..models import Quantity_Per_Size, ReservedShoe, Shoe, Color
cust_cart_views = Blueprint('cust_cart_views', __name__)
from .. import db


@cust_cart_views.before_request
@login_required
def login_to_access():
    """
    Acts as a middle ware that ensure none of this blueprints routes can be
    accessed if no user is currently logged in
    """
    pass


@cust_cart_views.route('/cart', methods=['GET'])
def display_cart_page():
    """
    Display the user's cart

    Returns:
        A rendered HTML template
    """
    cart = current_user.cart.shoes
    total_price = 0
    for shoe in cart:
        total_price += (shoe.quantity * shoe.reserved_shoe.price)
        
    return render_template('acct_mgmt/cart.html', 
    current_user=current_user, 
    cart=cart, 
    total_price=total_price)


@cust_cart_views.route('/cart', methods=['POST'])
def add_to_cart():
    """
    Adds a shoe to the user's cart

    Returns:
        Redirects the page to cart page again
    """
    id = int(request.form['shoe_id'])
    quantity = int(request.form['quantity'])
    color = (request.form['color'])
    size = float(request.form['size'])

    user_cart = current_user.cart
    shoe_in_cart = ReservedShoe.query.filter_by(
        cart_id=user_cart.id, 
        shoe_id=id,
        color=color,
        size=size).first()

    if shoe_in_cart:
        color = Color.query.filter_by(shoe_id=shoe_in_cart.shoe_id).first()
        max_quantity = Quantity_Per_Size.query.filter_by(color_id=color.id, size=shoe_in_cart.size).first()
        if max_quantity.quantity >= (shoe_in_cart.quantity + quantity):
            shoe_in_cart.quantity += quantity
            db.session.commit()
        # else you exceeded the max quantity
        else:
            return ('', 204)
    else:
        added_shoe = ReservedShoe(
            quantity = quantity,
            color=request.form['color'],
            size=request.form['size']
        )
        added_shoe.reserved_shoe = Shoe.query.get_or_404(id)
        db.session.add(added_shoe)
        current_user.cart.shoes.append(added_shoe)
        db.session.add(current_user)

        db.session.commit()

    return redirect(url_for('cust_cart_views.display_cart_page'))


@cust_cart_views.route('/cart/<int:id>', methods=['POST'])
def quick_add(id):
    """
    Adds to the quantity of a shoe in the user's cart

    Parameters:
        id (int): The id of the cart item

    Returns:_description_
        HTTP Reponse: Send the url for the display cart page and a http status
        of 200 for success
    """
    shoe = ReservedShoe.query.get_or_404(id)
    color = Color.query.filter_by(shoe_id=shoe.shoe_id).first()
    max_quantity = Quantity_Per_Size.query.filter_by(color_id=color.id, size=shoe.size).first()
    if max_quantity.quantity >= (shoe.quantity + 1):
        shoe.quantity += 1
    db.session.commit()
    return Response(url_for('cust_cart_views.display_cart_page'), 200)


@cust_cart_views.route('/cart/<int:id>', methods=['DELETE'])
def quick_remove(id):
    """
    Removes from the quantity of a shoe in the user's cart

    Parameters:
        id (int): The id of the cart item

    Returns:_description_
        HTTP Reponse: Send the url for the display cart page and a http status
        of 200 for success
    """
    shoe = ReservedShoe.query.get_or_404(id)
    shoe.quantity -= 1
    if shoe.quantity == 0:
        db.session.delete(shoe)
    db.session.commit()
    return Response(url_for('cust_cart_views.display_cart_page'), 200)


@cust_cart_views.route('/cart/remove/<int:id>', methods=['DELETE'])
def remove_from_cart(id):
    """
    Removes a shoe from the user's cart

    Parameters:
        id (int): The id of the cart item

    Returns:
        HTTP Reponse: Send the url for the display cart page and a http status
        of 200 for success
    """
    shoe = ReservedShoe.query.get_or_404(id)
    db.session.delete(shoe)
    db.session.commit()
    return Response(url_for('cust_cart_views.display_cart_page'), 200)

website/views/cust_catalog_views.py
"""
Manages all routes related to the shoe catalog that the customers see

Author: Mathew Owusu Jr
"""


from flask import Blueprint, render_template, request
from flask_login import current_user
from ..models import Shoe


PER_PAGE = 36
cust_catalog_views = Blueprint('cust_catalog_views', __name__)


@cust_catalog_views.route('/releases', methods=['GET'])
def releases_page():
    """
    Display all the shoes from the database

    Returns:
        A rendered HTML template
    """
    title = "New Releases"
    page = request.args.get('page', 1, type=int)
    collection = Shoe.query.paginate(page=page, per_page=PER_PAGE)
    routeUrl = 'cust_catalog_views.releases_page'

    return render_template('customer/catalog.html', 
    current_user=current_user, 
    title=title, 
    collection=collection, 
    routeUrl=routeUrl)


@cust_catalog_views.route('/mens/releases', methods=['GET'])
def mens_releases_page():
    """
    Display all the mens shoes from the database

    Returns:
        A rendered HTML template
    """
    title = "New Releases"
    page = request.args.get('page', 1, type=int)
    collection = Shoe.query.filter_by(audience="Men").paginate(page=page, per_page=PER_PAGE)
    routeUrl = 'cust_catalog_views.mens_releases_page'

    return render_template('customer/catalog.html', 
    title=title, 
    collection=collection, 
    routeUrl=routeUrl)


@cust_catalog_views.route('/womens/releases', methods=['GET'])
def womens_releases_page():
    """
    Display all the womens shoes from the database

    Returns:
        A rendered HTML template
    """
    title = "New Releases"
    page = request.args.get('page', 1, type=int)
    collection = Shoe.query.filter_by(audience="Women").paginate(page=page, per_page=PER_PAGE)
    routeUrl = 'cust_catalog_views.womens_releases_page'

    return render_template('customer/catalog.html', 
    title=title, 
    current_user=current_user, 
    collection=collection, 
    routeUrl=routeUrl)


@cust_catalog_views.route('/kids/releases', methods=['GET'])
def kids_releases_page():
    """
    Display all the kids shoes from the database

    Returns:
        A rendered HTML template
    """
    title = "New Releases"
    page = request.args.get('page', 1, type=int)
    collection = Shoe.query.filter_by(audience="Children").paginate(page=page, per_page=PER_PAGE)
    routeUrl = 'cust_catalog_views.kids_releases_page'

    return render_template('customer/catalog.html', 
    title=title, 
    current_user=current_user, 
    collection=collection, 
    routeUrl=routeUrl)


@cust_catalog_views.route('/<string:brand>/releases', methods=['GET'])
def brand_releases_page(brand):
    """
    Display all the shoes from a particular brand

    Parameters:
        brand (string): The name of the brand

    Returns:
        A rendered HTML template
    """
    title = brand + " New Releases"
    page = request.args.get('page', 1, type=int)
    collection = Shoe.query.filter(Shoe.brand.like('%'+brand+'%')).paginate(page=page, per_page=PER_PAGE)
    routeUrl = 'cust_catalog_views.brand_releases_page'

    return render_template('customer/catalog.html', 
    title=title, 
    current_user=current_user, 
    collection=collection, 
    routeUrl=routeUrl,
    brand=brand)


@cust_catalog_views.route('/releases/browse/<string:searchQuery>')
def search_any_product(searchQuery):
    """
    Display all the shoes that match the search term

    Parameters:
        searchQuery (string): The seach term

    Returns:
        A rendered HTML template
    """
    title = "Sneaker Head Releases"
    page = request.args.get('page', 1, type=int)
    collection = Shoe.query.filter(Shoe.name.like('%'+searchQuery+'%') | Shoe.brand.like('%'+searchQuery+'%')).paginate(page=page, per_page=PER_PAGE)
    routeUrl = 'cust_catalog_views.search_any_product'

    return render_template('customer/catalog.html', 
    title=title, 
    collection=collection, 
    routeUrl=routeUrl,
    searchQuery=searchQuery)


@cust_catalog_views.route('/product/<int:id>', methods=['GET'])
def display_product(id):
    """

    Parameters:
        id (int): The id of the shoe being displayed

    Returns:
        A rendered HTML template
    """
    shoe = Shoe.query.get_or_404(id)
    return render_template('customer/product.html', 
    current_user=current_user, 
    shoe=shoe)
    

website/views/home_view.py
"""
Manages all routes related to home

Author: Mathew Owusu Jr
"""

from flask import Blueprint, render_template
from flask_login import current_user
from ..models import Shoe
home_view = Blueprint('home_view', __name__)

@home_view.route('/')
@home_view.route('/home')
def home_page():
    """
    Fetches recently added shoes to the database and displays it on the home page

    Returns:
        A rendered HTML template
    """
    recently_added = Shoe.query.filter_by(audience='Men').order_by(Shoe.id.desc()).limit(5)
    brands = [
        "adidas",
        "aldo",
        "converse",
        "fila",
        "lacoste",
        "new balance",
        "nike",
        "Polo Ralph Lauren",
        "puma",
        "reebook",
        "sketchers",
        "steve madden",
        "timberland",
        "hilfiger",
        "under armour",
        "vans"
        ]
    
    return render_template("index.html", 
    current_user=current_user, 
    recently_added=recently_added, 
    brands=brands)

website/templates/admin_catalog.html
{% extends 'base.html' %}


{% block title %}
    Product Inventory
{% endblock %}


{% block body %}
    <h1>Welcome to the Inventory</h1>
    <!-- Add New Shoe -->
    <form action="/inventory" method="POST">
        <input type="text" name="name" placeholder="name" required>
        <input type="text" name="brand" placeholder="brand" required>
        
        <select name="audience" required>
            <option value="">select audience</option>
            <option value="Men">Men</option>
            <option value="Women">Women</option>
            <option value="Children">Children</option>
        </select>

        <input type="number" name="price" placeholder="price" required>
        <input type="submit" value="add to inventory">
    </form>

    <!-- List All Shoes -->
    <table>
        <tr>
            <th>Product ID</th>
            <th>Shoe Name</th>
            <th>Brand Name</th>
            <th>Price</th>
            <th>Update</th>
            <th>Delete</th>
        </tr>
        {% for shoe in inventory %}
            <tr>
                <form id="put-form" action="/inventory/{{ shoe.id }}" method="POST">
                    <td>{{ shoe.id }}</td>
                    <td>
                        <p>{{ shoe.name }}</p>
                    </td>
                    <td>
                        <p>{{ shoe.brand }}</p>
                    </td>
                    <td>
                        <p>{{ shoe.price }}</p>
                    </td>
                    <td>
                        <button onclick="redirectUrl('/inventory/{{shoe.id}}')">edit shoe</button>
                    </td>
                </form>
                <td>
                    <button onclick="sendDeleteRequest('/inventory/{{shoe.id}}')">remove shoe</button>
                </td> 
            </tr>
        {% endfor %}
    </table>
    
    <!-- <h1>Test</h1>
    <table>
        <tr>
            <th>Product ID</th>
            <th>Shoe Name</th>
            <th>Brand Name</th>
            <th>Price</th>
            <th>Update</th>
            <th>Delete</th>
        </tr>
        {% for shoe in inventory %}
            <tr>
                <form id="put-form" action="/inventory/{{ shoe.id }}" method="POST">
                    <td>{{ shoe.id }}</td>
                    <td>
                        <input type="text" name="name" placeholder="{{ shoe.name }}" required>
                    </td>
                    <td>
                        <input type="text" name="brand" placeholder="{{ shoe.brand }}" required>
                    </td>
                    <td>
                        <input type="number" name="price" placeholder="{{ shoe.price }}" required>
                    </td>
                    <td>
                        <button type="submit">update item</button>
                    </td>
                </form>
                <td>
                    <button onclick="sendDeleteRequest('/inventory/{{shoe.id}}')">remove shoe</button>
                </td> 
            </tr>
            
            
            {% if shoe.colors == [] %}
                <p>not ready for sale, needs color options, edit shoe to fix this</p>
            {% else %}
                {% for color in shoe.colors %}
                    {% if color.quantity == [] %}
                        <p>not ready for sale, needs size options, edit shoe to fix this</p>
                    {% endif %}
                {% endfor %}
            {% endif %} 

            
        {% endfor %}
    </table> -->
{% endblock %}

website/templates/admin_catalog_product.html
{% extends 'base.html' %}

{% block title %}{{shoe.name}}{% endblock %}

{% block body %}
    <h1>Shoe Details</h1>
    <p>{{ shoe.name }}</p>
    <p>{{ shoe.brand }}</p>
    <p>{{ shoe.audience }}</p>
    <p>{{ shoe.price }}</p>
    <form id="put-form" action="/inventory/{{ shoe.id }}" method="POST">
            <input type="text" name="name" value="{{ shoe.name }}">
            <input type="text" name="brand" value="{{ shoe.brand }}">
            <!-- <input type="text" name="audience" value="{{ shoe.audience }}"> -->
            <select name="audience" >
                <option value="{{ shoe.audience }}">{{ shoe.audience }}</option>
                <option value="Men">Men</option>
                <option value="Women">Women</option>
                <option value="Children">Children</option>
            </select>

            <input type="number" name="price" value="{{ shoe.price }}">
            <button type="submit">update item</button>
    </form>
    <div id="colors">
        <h2>Shoe Colors</h2>
        {% for color in shoe.colors%}
            <!-- <p>{{ color.color }}</p> -->
            <form id="put-form" action="/inventory/{{shoe.id}}/{{color.id}}" method="POST">
                <input type="text" name="color" value="{{color.color}}">
                <input type="submit" value="edit color name">
            </form>
            <button onclick="sendDeleteRequest('/inventory/{{shoe.id}}/{{color.id}}')">delete color</button>
            {% endfor %}  
        <br>
        <button onclick="addColor('/inventory/{{shoe.id}}')">add color</button>
    </div>  
    <div id="quantities">
        <h2>Quantity of shoes per each size</h2>
        {% for color in shoe.colors%}
            <h4>Quantites for the color {{ color.color }}</h4>
            {% for quantity in color.quan_per_size%}
                <form id="put-form" action="/inventory/{{shoe.id}}/{{color.id}}/{{quantity.id}}" method="POST">
                    <p>{{ quantity.size }}</p>
                    <input type="number" name="quantity" min= "0" value="{{quantity.quantity}}">
                    <input type="submit" value="edit quantity">
                </form>
                <button onclick="sendDeleteRequest('/inventory/{{shoe.id}}/{{color.id}}/{{quantity.id}}')">remove size</button>
            {% endfor %}
            <br>
            <button onclick="addSize('/inventory/{{shoe.id}}/{{color.id}}')">Add a size</button>
        {% endfor %}
        <!-- <br> -->
    </div>
{% endblock%}

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script type="text/javascript" src="{{ url_for('static', filename='main.js') }}"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='http-methods.js') }}"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='dist/main.css') }}">
    <link rel = "icon" href ="{{ url_for('static', filename='shoe_icon.png') }}" type = "image/x-icon">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <nav class="nav-bar">
        <div class="mobile-nav">
            <a href="#" class="toggle-button" onclick="navToggle()">
                <span class="bar"></span>
                <span class="bar"></span>
                <span class="bar"></span>
            </a>
            <a class="nav-title">Sneaker Head</a>
        </div>
        <div class="nav-links">
            <ul>
                <div class="nav-releases">
                    <li><a href="{{ url_for('home_view.home_page') }}">Home</a></li>
                    <li><a href="{{ url_for('cust_catalog_views.releases_page') }}">New Releases</a></li>
                    <li><a href="{{ url_for('cust_catalog_views.mens_releases_page') }}">Mens</a></li>
                    <li><a href="{{ url_for('cust_catalog_views.womens_releases_page') }}">Womens</a></li>
                    <li><a href="{{ url_for('cust_catalog_views.kids_releases_page') }}">Kids</a></li>
                </div>
                
                <li>
                    <a>
                        <form id="search" action="/releases/browse/" method="GET">
                            <input type="search" name="search" placeholder="Search">
                        </form>
                    </a>
                </li>
                
                <div class="acct-block">
                    {% if current_user.is_authenticated %}
                        <li>
                            <a href="{{url_for('cust_cart_views.display_cart_page')}}">Cart</a>
                        </li>
                        <li>
                            <a href="{{ url_for( 'acct_mgmt_views.display_account_page', user_id=current_user.id ) }}">{{current_user.firstname}}</a>
                        </li>
                        <li>
                            <a href="{{url_for('acct_mgmt_views.logout')}}"">Sign Out</a>
                        </li>
                    {% else %}
                        <li>
                            <a href="{{url_for('acct_mgmt_views.display_signup_page')}}">Join Us</a>
                        </li>
                        <li>
                            <a href="{{url_for('acct_mgmt_views.display_login_page')}}"">Sign In</a>
                        </li>
                    {% endif %}
                </div>  
            </ul> 
        </div>
    </nav>

    <div class="content">
        {% block body %}{% endblock %}
    </div>

    <footer>
        <p>Author: Mathew Owusu Jr</p>
    </footer>
</body>
</html>

website/templates/cust_catalog_product.html
{% extends 'base.html' %}

{% block title %}{{shoe.name}}{% endblock %}

{% block body %}
    <h1>Shoe Details</h1>
    <p>{{ shoe.name }}</p>
    <p>{{ shoe.brand }}</p>
    <p>{{ shoe.audience }}</p>
    <p>{{ shoe.price }}</p>
    <form id="add-to-cart-form" action="{{url_for('cust_cart_views.add_to_cart')}}" method="POST">
        <input type="hidden" name="shoe_id" value="{{shoe.id}}">
        <select name="quantity" required>
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
            <option value="4">4</option>
            <option value="5">5</option>
        </select>
        <input type="submit" value="Add to Cart">
    </form>
{% endblock%}

website/templates/home.html
{% extends 'base.html' %}


{% block title %}
    Sneaker Heads. We Got You.
{% endblock %}


{% block body %}
    <!-- Recently Added Shoes -->
    <div class="collections">
        <h2>New Shoe Arrivals</h2>
        <ul>
            {% for shoe in recently_added %}
                <li onclick="redirectUrl('{{url_for('cust_catalog_views.display_product', id=shoe.id)}}')">
                    <a>{{ shoe.name  }}</a>
                    <p>${{ shoe.price  }}</p>
                </li>
            {% endfor %}
        </ul>
    </div>

    <div class="collections brand-collection">
        <h2>Shop our Brands</h2>
        <ul>
            {% for brand in brands %}
                <li onclick="redirectUrl('{{url_for('cust_catalog_views.brand_releases_page', brand=brand)}}')">
                    <a>
                        {{brand}}
                    </a>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

website/templates/index.html
{% extends 'base.html' %}


{% block title %}
    Sneaker Head. We Got You.
{% endblock %}


{% block body %}
    <div class="new-arrivals">
        <h2>New Shoe Arrivals</h2>
        <ul>
            {% for shoe in recently_added %}
                <li class="arrival-card" onclick="redirectUrl('{{url_for('cust_catalog_views.display_product', id=shoe.id)}}')">
                    <p>{{ shoe.name  }}</p>
                    <p>Colors: {{shoe.colors | length }}</p>
                    <p>${{ shoe.price  }}</p>
                </li>
            {% endfor %}
        </ul>
    </div>

    <div class="collections brand-collection">
        <h2>Shop Some of Our Brands</h2>
        <ul>
            {% for brand in brands %}
                <li class="item-card" onclick="redirectUrl('{{url_for('cust_catalog_views.brand_releases_page', brand=brand)}}')">
                    <a>
                        {{brand}}
                    </a>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}